config/routes.rb
Reemindme::Application.routes.draw do
  resources :text_msgs

  resources :requests

  resources :reminders

end

app/models/text_msg.rb
class TextMsg < ActiveRecord::Base
  
  after_save :create_request
  
private

  def create_request
    Request.create!(:phrase => self.Body)
  end
  
end

# == Schema Information
#
# Table name: text_msgs
#
#  id            :integer         not null, primary key
#  AccountSid    :string(255)
#  Body          :string(255)
#  ToZip         :string(255)
#  FromState     :string(255)
#  ToCity        :string(255)
#  SmsSid        :string(255)
#  ToState       :string(255)
#  To            :string(255)
#  ToCountry     :string(255)
#  FromCountry   :string(255)
#  SmsMessageSid :string(255)
#  ApiVersion    :string(255)
#  FromCity      :string(255)
#  SmsStatus     :string(255)
#  From          :string(255)
#  FromZip       :string(255)
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#

app/controllers/text_msgs_controller.rb
class TextMsgsController < ApplicationController
  
  def index
    @text_msgs = TextMsg.all
  end
  
  def new
    @text_msg = TextMsg.new
  end
  
  def create
    if params[:text_msg]
      @text_msg = TextMsg.new(params[:text_msg])
    else
      @text_msg = TextMsg.new(:Body => params[:Body])
    end
    if @text_msg.save
      # render :text => "<Response><Sms>Got it!</Sms></Response>"
      render :text => ""
    else
      # report this error
      render :text => "<Response><Sms>something went wrong</Sms></Response>"
    end
  end
    
end

app/helpers/text_msgs_helper.rb
module TextMsgsHelper
end

app/views/text_msgs/_form.html.erb
<%= form_for(@text_msg) do |f| %>
  <% if @text_msg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text_msg.errors.count, "error") %> prohibited this text_msg from being saved:</h2>

      <ul>
      <% @text_msg.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :AccountSid %><br />
    <%= f.text_field :AccountSid %>
  </div>
  <div class="field">
    <%= f.label :Body %><br />
    <%= f.text_field :Body %>
  </div>
  <div class="field">
    <%= f.label :ToZip %><br />
    <%= f.text_field :ToZip %>
  </div>
  <div class="field">
    <%= f.label :FromState %><br />
    <%= f.text_field :FromState %>
  </div>
  <div class="field">
    <%= f.label :ToCity %><br />
    <%= f.text_field :ToCity %>
  </div>
  <div class="field">
    <%= f.label :SmsSid %><br />
    <%= f.text_field :SmsSid %>
  </div>
  <div class="field">
    <%= f.label :ToState %><br />
    <%= f.text_field :ToState %>
  </div>
  <div class="field">
    <%= f.label :To %><br />
    <%= f.text_field :To %>
  </div>
  <div class="field">
    <%= f.label :ToCountry %><br />
    <%= f.text_field :ToCountry %>
  </div>
  <div class="field">
    <%= f.label :FromCountry %><br />
    <%= f.text_field :FromCountry %>
  </div>
  <div class="field">
    <%= f.label :SmsMessageSid %><br />
    <%= f.text_field :SmsMessageSid %>
  </div>
  <div class="field">
    <%= f.label :ApiVersion %><br />
    <%= f.text_field :ApiVersion %>
  </div>
  <div class="field">
    <%= f.label :FromCity %><br />
    <%= f.text_field :FromCity %>
  </div>
  <div class="field">
    <%= f.label :SmsStatus %><br />
    <%= f.text_field :SmsStatus %>
  </div>
  <div class="field">
    <%= f.label :From %><br />
    <%= f.text_field :From %>
  </div>
  <div class="field">
    <%= f.label :FromZip %><br />
    <%= f.text_field :FromZip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/text_msgs/edit.html.erb
<h1>Editing text_msg</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_msg %> |
<%= link_to 'Back', text_msgs_path %>

app/views/text_msgs/index.html.erb
<h1>Listing text_msgs</h1>

<table>
  <tr>
    <th>Accountsid</th>
    <th>Body</th>
    <th>Tozip</th>
    <th>Fromstate</th>
    <th>Tocity</th>
    <th>Smssid</th>
    <th>Tostate</th>
    <th>To</th>
    <th>Tocountry</th>
    <th>Fromcountry</th>
    <th>Smsmessagesid</th>
    <th>Apiversion</th>
    <th>Fromcity</th>
    <th>Smsstatus</th>
    <th>From</th>
    <th>Fromzip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @text_msgs.each do |text_msg| %>
  <tr>
    <td><%= text_msg.AccountSid %></td>
    <td><%= text_msg.Body %></td>
    <td><%= text_msg.ToZip %></td>
    <td><%= text_msg.FromState %></td>
    <td><%= text_msg.ToCity %></td>
    <td><%= text_msg.SmsSid %></td>
    <td><%= text_msg.ToState %></td>
    <td><%= text_msg.To %></td>
    <td><%= text_msg.ToCountry %></td>
    <td><%= text_msg.FromCountry %></td>
    <td><%= text_msg.SmsMessageSid %></td>
    <td><%= text_msg.ApiVersion %></td>
    <td><%= text_msg.FromCity %></td>
    <td><%= text_msg.SmsStatus %></td>
    <td><%= text_msg.From %></td>
    <td><%= text_msg.FromZip %></td>
    <td><%= link_to 'Show', text_msg %></td>
    <td><%= link_to 'Edit', edit_text_msg_path(text_msg) %></td>
    <td><%= link_to 'Destroy', text_msg, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Text msg', new_text_msg_path %>

app/views/text_msgs/new.html.erb
<h1>New text_msg</h1>

<%= render 'form' %>

<%= link_to 'Back', text_msgs_path %>

app/views/text_msgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Accountsid:</b>
  <%= @text_msg.AccountSid %>
</p>

<p>
  <b>Body:</b>
  <%= @text_msg.Body %>
</p>

<p>
  <b>Tozip:</b>
  <%= @text_msg.ToZip %>
</p>

<p>
  <b>Fromstate:</b>
  <%= @text_msg.FromState %>
</p>

<p>
  <b>Tocity:</b>
  <%= @text_msg.ToCity %>
</p>

<p>
  <b>Smssid:</b>
  <%= @text_msg.SmsSid %>
</p>

<p>
  <b>Tostate:</b>
  <%= @text_msg.ToState %>
</p>

<p>
  <b>To:</b>
  <%= @text_msg.To %>
</p>

<p>
  <b>Tocountry:</b>
  <%= @text_msg.ToCountry %>
</p>

<p>
  <b>Fromcountry:</b>
  <%= @text_msg.FromCountry %>
</p>

<p>
  <b>Smsmessagesid:</b>
  <%= @text_msg.SmsMessageSid %>
</p>

<p>
  <b>Apiversion:</b>
  <%= @text_msg.ApiVersion %>
</p>

<p>
  <b>Fromcity:</b>
  <%= @text_msg.FromCity %>
</p>

<p>
  <b>Smsstatus:</b>
  <%= @text_msg.SmsStatus %>
</p>

<p>
  <b>From:</b>
  <%= @text_msg.From %>
</p>

<p>
  <b>Fromzip:</b>
  <%= @text_msg.FromZip %>
</p>


<%= link_to 'Edit', edit_text_msg_path(@text_msg) %> |
<%= link_to 'Back', text_msgs_path %>